Apply patch (requested by jmc in ticket #114): Update XFree86 to version 4.5.0.

diff --git a/xfree/xc/extras/freetype2/configure b/xfree/xc/extras/freetype2/configure
--- a/xfree/xc/extras/freetype2/configure
+++ b/xfree/xc/extras/freetype2/configure
@@ -5,7 +5,6 @@
 # This should re-generate the following files:
 #
 #   config.mk
-#   Jamfile
 #   install
 #
 
@@ -14,9 +13,14 @@ if test "x$GNUMAKE" = x; then
 fi
 
 if test -z "`$GNUMAKE -v 2>/dev/null | grep GNU`"; then
-  echo "Sorry, GNU make is required to build FreeType2." >&2
-  echo "Please try \`GNUMAKE=<GNU make command name> $0'." >&2
-  exit 1
+  if test -z "`$GNUMAKE -v 2>/dev/null | grep makepp`"; then
+    echo "GNU make (>= 3.79.1) or makepp (>= 1.19) is required to build FreeType2." >&2
+    echo "Please try" >&2
+    echo "  \`GNUMAKE=<GNU make command name> $0'." >&2
+    echo "or >&2"
+    echo "  \`GNUMAKE=\"makepp --norc-substitution\" $0'." >&2
+    exit 1
+  fi
 fi
 
 # Uh, oh.  This is taken from autoconf.  They know what they are doing...
@@ -46,11 +50,13 @@ abs_ft2_dir=`cd "$ft2_dir" && pwd`
 # build a dummy Makefile if we are not building in the source tree
 
 if test "$abs_curr_dir" != "$abs_ft2_dir"; then
-  echo "OBJ_DIR=$abs_curr_dir"          > Makefile
-  echo "TOP_DIR=$abs_ft2_dir"          >> Makefile
-  echo "OBJ_BUILD=$abs_curr_dir"       >> Makefile
-  echo "LIBTOOL=$abs_curr_dir/libtool" >> Makefile
-  echo "include $abs_ft2_dir/Makefile" >> Makefile
+  mkdir reference
+  echo "TOP_DIR=$abs_ft2_dir"             > Makefile
+  echo "OBJ_DIR=$abs_curr_dir"           >> Makefile
+  echo "OBJ_BUILD=$abs_curr_dir"         >> Makefile
+  echo "DOC_DIR=$abs_curr_dir/reference" >> Makefile
+  echo "LIBTOOL=$abs_curr_dir/libtool"   >> Makefile
+  echo "include $abs_ft2_dir/Makefile"   >> Makefile
 fi
 
 # call make
